In [3]:
#Description 
''' The Tensor is basic building block used to represent the data. Tensors can be thought of as a multidimensional array similar to a matrix but with arbitrary numbers of dimensions.
Tensors can hold various data types such as integers,floating-point and strings.
Tensors have various properties such as shape,size, rank and dimensions and they can be added,multiplied and manipulated in various way to perform mathematical operations.
Tensors are essential in Deeplearning framework such as tensorflow and pytorch
'''

' The Tensor is basic building block used to represent the data. Tensors can be thought of as a multidimensional array similar to a matrix but with arbitrary numbers of dimensions.\nTensors can hold various data types such as integers,floating-point and strings.\nTensors have various properties such as shape,size, rank and dimensions and they can be added,multiplied and manipulated in various way to perform mathematical operations.\nTensors are essential in Deeplearning framework such as tensorflow and pytorch\n'

In [13]:
import tensorflow as tf 
import numpy as np 
#Creating a tensor using numpy
t=np.array([[1,2,3],[4,5,6]])

In [14]:
#Creating a tensor using tensorflow library
p=tf.constant([[1,2,3],[4,5,6]])

In [16]:
#Performing addition 
t1=t+2
p1=p+3
print(t1)
print(p1)

[[3 4 5]
 [6 7 8]]
tf.Tensor(
[[4 5 6]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [17]:
#Performing Multiplication
t2=t*3
p2=p*3
print(t2)
print(p2)

[[ 3  6  9]
 [12 15 18]]
tf.Tensor(
[[ 3  6  9]
 [12 15 18]], shape=(2, 3), dtype=int32)


In [18]:
#Performing exponential 
t3=np.power(t,2)
p3=np.power(p,3)
print(t3)
print(p3)

[[ 1  4  9]
 [16 25 36]]
[[  1   8  27]
 [ 64 125 216]]


In [20]:
#Performing transpose
t4=np.transpose(t)
print(t4)
p4=np.transpose(p)
print(p4)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
