In [5]:
'''Tensors are the basic building block used to represent data 
Tensor can be thought of as a multidimensional array similar to matrix but with arbitrary number of d
dimensions.Tensors can hold the various values such as integer,floating point and string.
Tensors have various properties such as size shape rank and dimensionality and they can be added multi
plied and manipulated in various ways to perform mathematical operations. Tensors are essential in 
deeplearning frameworks such as Tensorflow and pytorch
'''

'Tensors are the basic building block used to represent data \nTensor can be thought of as a multidimensional array similar to matrix but with arbitrary number of d\ndimensions.Tensors can hold the various values such as integer,floating point and string.\nTensors have various properties such as size shape rank and dimensionality and they can be added multi\nplied and manipulated in various ways to perform mathematical operations. Tensors are essential in \ndeeplearning frameworks such as Tensorflow and pytorch\n'

In [6]:
import numpy as np 
import tensorflow as tf 
#Take the input of rows and cols 
row=eval(input("Enter the number of rows: "))
cols=eval(input("Enter the number of cols : "))
#save the tensor with the given rows and cols 
tensor=np.empty((row,cols))

Enter the number of rows: 2
Enter the number of cols : 2


In [7]:
#Taking input for rows and columns
for i in range(row):
    for j in range(cols):
        tensor[i][j]=eval(input(f"Enter the value of [{i}][{j}]: "))
print(tensor)

Enter the value of [0][0]: 1
Enter the value of [0][1]: 2
Enter the value of [1][0]: 3
Enter the value of [1][1]: 4
[[1. 2.]
 [3. 4.]]


In [14]:
#Splitting of Tensors
sp=int(input("Enter the dimesion(0 for columns and 1 for rows): "))
s=np.split(tensor,2,axis=sp)
#in split first we need to give array and second how many equal parts do we need to divide the array and the third is axis
print(s)

Enter the dimesion(0 for columns and 1 for rows): 0
[array([[1., 2.]]), array([[3., 4.]])]


In [16]:
#Merging of Tensors
m=np.concatenate((s),axis=sp)#here we are merging the tensors that we have seperated using split function.
print(m)

[[1. 2.]
 [3. 4.]]


In [17]:
#Statictics operation 
mean=np.mean(tensor)
print("Mean: ",mean)

Mean:  2.5


In [18]:
#2 Median
med=np.median(tensor)
print(med)

2.5


In [19]:
#standard deviation
std=np.std(tensor)
print(std)

1.118033988749895


In [20]:
var=np.var(tensor)
print(var)

1.25


In [22]:
#finding the minimum and maximum 
maxi=np.max(tensor)
mini=np.min(tensor)
print(maxi)
print(mini)

4.0
1.0


In [23]:
#Transpose 
trans=np.transpose(tensor)
print(trans)

[[1. 3.]
 [2. 4.]]


In [24]:
#dot product 
dot=np.dot(trans,tensor)
print(dot)

[[10. 14.]
 [14. 20.]]


In [25]:
""" np.split(array,division,axis)--> np.split(tensor,2,axis=0)
    np.concatenate((arrays),axis)--> np.concatenate((s),axis=sp)
    np.mean(array)--> np.mean(tensor)
    np.median(array)-->np.median(tensor)
    np.max(array)-->np.max(tensor)
    np.min(array)-->np.min(tensor)
    np.std(array)-->np.std(tensor)
    np.var(array)-->np.var(tensor)
    np.transpose(array)-->np.transpose(tensor)
    np.dot(array1,array2)-->np.transpose(trans,tensor)
"""

' np.split(array,division,axis)--> np.split(tensor,2,axis=0)\n    np.concatenate((arrays),axis)--> np.concatenate((s),axis=sp)\n    np.mean(array)--> np.mean(tensor)\n    np.median(array)-->np.median(tensor)\n    np.max(array)-->np.max(tensor)\n    np.min(array)-->np.min(tensor)\n    np.std(array)-->np.std(tensor)\n    np.var(array)-->np.var(tensor)\n    np.transpose(array)-->np.transpose(tensor)\n    np.dot(array1,array2)-->np.transpose(trans,tensor)\n'